/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.dayoffs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DaysOffCounter service. Represents a row in the &quot;TimeTracking_DaysOffCounter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.dayoffs.model.impl.DaysOffCounterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.dayoffs.model.impl.DaysOffCounterImpl}.
 * </p>
 *
 * @author Laszlo Hudak
 * @see DaysOffCounter
 * @see com.liferay.timetracking.dayoffs.model.impl.DaysOffCounterImpl
 * @see com.liferay.timetracking.dayoffs.model.impl.DaysOffCounterModelImpl
 * @generated
 */
public interface DaysOffCounterModel extends AuditedModel,
	BaseModel<DaysOffCounter> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a days off counter model instance should use the {@link DaysOffCounter} interface instead.
	 */

	/**
	 * Returns the primary key of this days off counter.
	 *
	 * @return the primary key of this days off counter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this days off counter.
	 *
	 * @param primaryKey the primary key of this days off counter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the day off counter ID of this days off counter.
	 *
	 * @return the day off counter ID of this days off counter
	 */
	public long getDayOffCounterId();

	/**
	 * Sets the day off counter ID of this days off counter.
	 *
	 * @param dayOffCounterId the day off counter ID of this days off counter
	 */
	public void setDayOffCounterId(long dayOffCounterId);

	/**
	 * Returns the company ID of this days off counter.
	 *
	 * @return the company ID of this days off counter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this days off counter.
	 *
	 * @param companyId the company ID of this days off counter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this days off counter.
	 *
	 * @return the user ID of this days off counter
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this days off counter.
	 *
	 * @param userId the user ID of this days off counter
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this days off counter.
	 *
	 * @return the user uuid of this days off counter
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this days off counter.
	 *
	 * @param userUuid the user uuid of this days off counter
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this days off counter.
	 *
	 * @return the user name of this days off counter
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this days off counter.
	 *
	 * @param userName the user name of this days off counter
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this days off counter.
	 *
	 * @return the create date of this days off counter
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this days off counter.
	 *
	 * @param createDate the create date of this days off counter
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this days off counter.
	 *
	 * @return the modified date of this days off counter
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this days off counter.
	 *
	 * @param modifiedDate the modified date of this days off counter
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the worker user ID of this days off counter.
	 *
	 * @return the worker user ID of this days off counter
	 */
	public long getWorkerUserId();

	/**
	 * Sets the worker user ID of this days off counter.
	 *
	 * @param workerUserId the worker user ID of this days off counter
	 */
	public void setWorkerUserId(long workerUserId);

	/**
	 * Returns the worker user uuid of this days off counter.
	 *
	 * @return the worker user uuid of this days off counter
	 * @throws SystemException if a system exception occurred
	 */
	public String getWorkerUserUuid() throws SystemException;

	/**
	 * Sets the worker user uuid of this days off counter.
	 *
	 * @param workerUserUuid the worker user uuid of this days off counter
	 */
	public void setWorkerUserUuid(String workerUserUuid);

	/**
	 * Returns the worker user name of this days off counter.
	 *
	 * @return the worker user name of this days off counter
	 */
	@AutoEscape
	public String getWorkerUserName();

	/**
	 * Sets the worker user name of this days off counter.
	 *
	 * @param workerUserName the worker user name of this days off counter
	 */
	public void setWorkerUserName(String workerUserName);

	/**
	 * Returns the rule ID of this days off counter.
	 *
	 * @return the rule ID of this days off counter
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this days off counter.
	 *
	 * @param ruleId the rule ID of this days off counter
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the year of this days off counter.
	 *
	 * @return the year of this days off counter
	 */
	public int getYear();

	/**
	 * Sets the year of this days off counter.
	 *
	 * @param year the year of this days off counter
	 */
	public void setYear(int year);

	/**
	 * Returns the all days of this days off counter.
	 *
	 * @return the all days of this days off counter
	 */
	public int getAllDays();

	/**
	 * Sets the all days of this days off counter.
	 *
	 * @param allDays the all days of this days off counter
	 */
	public void setAllDays(int allDays);

	/**
	 * Returns the remaining days of this days off counter.
	 *
	 * @return the remaining days of this days off counter
	 */
	public int getRemainingDays();

	/**
	 * Sets the remaining days of this days off counter.
	 *
	 * @param remainingDays the remaining days of this days off counter
	 */
	public void setRemainingDays(int remainingDays);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DaysOffCounter daysOffCounter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DaysOffCounter> toCacheModel();

	@Override
	public DaysOffCounter toEscapedModel();

	@Override
	public DaysOffCounter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}