/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.dayoffs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DaysOfYear service. Represents a row in the &quot;TimeTracking_DaysOfYear&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.dayoffs.model.impl.DaysOfYearModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.dayoffs.model.impl.DaysOfYearImpl}.
 * </p>
 *
 * @author Laszlo Hudak
 * @see DaysOfYear
 * @see com.liferay.timetracking.dayoffs.model.impl.DaysOfYearImpl
 * @see com.liferay.timetracking.dayoffs.model.impl.DaysOfYearModelImpl
 * @generated
 */
public interface DaysOfYearModel extends AttachedModel, AuditedModel,
	BaseModel<DaysOfYear> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a days of year model instance should use the {@link DaysOfYear} interface instead.
	 */

	/**
	 * Returns the primary key of this days of year.
	 *
	 * @return the primary key of this days of year
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this days of year.
	 *
	 * @param primaryKey the primary key of this days of year
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the day of year ID of this days of year.
	 *
	 * @return the day of year ID of this days of year
	 */
	public long getDayOfYearId();

	/**
	 * Sets the day of year ID of this days of year.
	 *
	 * @param dayOfYearId the day of year ID of this days of year
	 */
	public void setDayOfYearId(long dayOfYearId);

	/**
	 * Returns the company ID of this days of year.
	 *
	 * @return the company ID of this days of year
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this days of year.
	 *
	 * @param companyId the company ID of this days of year
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this days of year.
	 *
	 * @return the user ID of this days of year
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this days of year.
	 *
	 * @param userId the user ID of this days of year
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this days of year.
	 *
	 * @return the user uuid of this days of year
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this days of year.
	 *
	 * @param userUuid the user uuid of this days of year
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this days of year.
	 *
	 * @return the user name of this days of year
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this days of year.
	 *
	 * @param userName the user name of this days of year
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this days of year.
	 *
	 * @return the create date of this days of year
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this days of year.
	 *
	 * @param createDate the create date of this days of year
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this days of year.
	 *
	 * @return the modified date of this days of year
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this days of year.
	 *
	 * @param modifiedDate the modified date of this days of year
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the day ID of this days of year.
	 *
	 * @return the day ID of this days of year
	 */
	public Date getDayId();

	/**
	 * Sets the day ID of this days of year.
	 *
	 * @param dayId the day ID of this days of year
	 */
	public void setDayId(Date dayId);

	/**
	 * Returns the rule ID of this days of year.
	 *
	 * @return the rule ID of this days of year
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this days of year.
	 *
	 * @param ruleId the rule ID of this days of year
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the fully qualified class name of this days of year.
	 *
	 * @return the fully qualified class name of this days of year
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this days of year.
	 *
	 * @return the class name ID of this days of year
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this days of year.
	 *
	 * @param classNameId the class name ID of this days of year
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this days of year.
	 *
	 * @return the class p k of this days of year
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this days of year.
	 *
	 * @param classPK the class p k of this days of year
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DaysOfYear daysOfYear);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DaysOfYear> toCacheModel();

	@Override
	public DaysOfYear toEscapedModel();

	@Override
	public DaysOfYear toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}