/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.dayoffs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Rule service. Represents a row in the &quot;TimeTracking_Rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.dayoffs.model.impl.RuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.dayoffs.model.impl.RuleImpl}.
 * </p>
 *
 * @author LÃ¡szlÃ³ HudÃ¡k
 * @see Rule
 * @see com.liferay.timetracking.dayoffs.model.impl.RuleImpl
 * @see com.liferay.timetracking.dayoffs.model.impl.RuleModelImpl
 * @generated
 */
public interface RuleModel extends AuditedModel, BaseModel<Rule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rule model instance should use the {@link Rule} interface instead.
	 */

	/**
	 * Returns the primary key of this rule.
	 *
	 * @return the primary key of this rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rule.
	 *
	 * @param primaryKey the primary key of this rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rule ID of this rule.
	 *
	 * @return the rule ID of this rule
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this rule.
	 *
	 * @param ruleId the rule ID of this rule
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the company ID of this rule.
	 *
	 * @return the company ID of this rule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rule.
	 *
	 * @param companyId the company ID of this rule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this rule.
	 *
	 * @return the user ID of this rule
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this rule.
	 *
	 * @param userId the user ID of this rule
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rule.
	 *
	 * @return the user uuid of this rule
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rule.
	 *
	 * @param userUuid the user uuid of this rule
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this rule.
	 *
	 * @return the user name of this rule
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this rule.
	 *
	 * @param userName the user name of this rule
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this rule.
	 *
	 * @return the create date of this rule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this rule.
	 *
	 * @param createDate the create date of this rule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rule.
	 *
	 * @return the modified date of this rule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rule.
	 *
	 * @param modifiedDate the modified date of this rule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this rule.
	 *
	 * @return the name of this rule
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rule.
	 *
	 * @param name the name of this rule
	 */
	public void setName(String name);

	/**
	 * Returns the multiplier of this rule.
	 *
	 * @return the multiplier of this rule
	 */
	public double getMultiplier();

	/**
	 * Sets the multiplier of this rule.
	 *
	 * @param multiplier the multiplier of this rule
	 */
	public void setMultiplier(double multiplier);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Rule rule);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Rule> toCacheModel();

	@Override
	public Rule toEscapedModel();

	@Override
	public Rule toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}