/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.dayoffs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Ruling service. Represents a row in the &quot;TimeTracking_Ruling&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.dayoffs.model.impl.RulingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.dayoffs.model.impl.RulingImpl}.
 * </p>
 *
 * @author LĂˇszlĂł HudĂˇk
 * @see Ruling
 * @see com.liferay.timetracking.dayoffs.model.impl.RulingImpl
 * @see com.liferay.timetracking.dayoffs.model.impl.RulingModelImpl
 * @generated
 */
public interface RulingModel extends BaseModel<Ruling>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ruling model instance should use the {@link Ruling} interface instead.
	 */

	/**
	 * Returns the primary key of this ruling.
	 *
	 * @return the primary key of this ruling
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ruling.
	 *
	 * @param primaryKey the primary key of this ruling
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rule ID of this ruling.
	 *
	 * @return the rule ID of this ruling
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this ruling.
	 *
	 * @param ruleId the rule ID of this ruling
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the group ID of this ruling.
	 *
	 * @return the group ID of this ruling
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ruling.
	 *
	 * @param groupId the group ID of this ruling
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ruling.
	 *
	 * @return the company ID of this ruling
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ruling.
	 *
	 * @param companyId the company ID of this ruling
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ruling.
	 *
	 * @return the user ID of this ruling
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ruling.
	 *
	 * @param userId the user ID of this ruling
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ruling.
	 *
	 * @return the user uuid of this ruling
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ruling.
	 *
	 * @param userUuid the user uuid of this ruling
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ruling.
	 *
	 * @return the user name of this ruling
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ruling.
	 *
	 * @param userName the user name of this ruling
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ruling.
	 *
	 * @return the create date of this ruling
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ruling.
	 *
	 * @param createDate the create date of this ruling
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ruling.
	 *
	 * @return the modified date of this ruling
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ruling.
	 *
	 * @param modifiedDate the modified date of this ruling
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the rule name of this ruling.
	 *
	 * @return the rule name of this ruling
	 */
	@AutoEscape
	public String getRuleName();

	/**
	 * Sets the rule name of this ruling.
	 *
	 * @param ruleName the rule name of this ruling
	 */
	public void setRuleName(String ruleName);

	/**
	 * Returns the multiplier of this ruling.
	 *
	 * @return the multiplier of this ruling
	 */
	public double getMultiplier();

	/**
	 * Sets the multiplier of this ruling.
	 *
	 * @param multiplier the multiplier of this ruling
	 */
	public void setMultiplier(double multiplier);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Ruling ruling);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Ruling> toCacheModel();

	@Override
	public Ruling toEscapedModel();

	@Override
	public Ruling toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}