/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.activities.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.timetracking.activities.model.ActivityAssignment;
import com.liferay.timetracking.activities.service.ActivityAssignmentLocalService;
import com.liferay.timetracking.activities.service.persistence.ActivityAssignmentPersistence;
import com.liferay.timetracking.activities.service.persistence.ActivityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the activity assignment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.timetracking.activities.service.impl.ActivityAssignmentLocalServiceImpl}.
 * </p>
 *
 * @author Laszlo Hudak, Adam T. Nagy
 * @see com.liferay.timetracking.activities.service.impl.ActivityAssignmentLocalServiceImpl
 * @see com.liferay.timetracking.activities.service.ActivityAssignmentLocalServiceUtil
 * @generated
 */
public abstract class ActivityAssignmentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ActivityAssignmentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.timetracking.activities.service.ActivityAssignmentLocalServiceUtil} to access the activity assignment local service.
	 */

	/**
	 * Adds the activity assignment to the database. Also notifies the appropriate model listeners.
	 *
	 * @param activityAssignment the activity assignment
	 * @return the activity assignment that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ActivityAssignment addActivityAssignment(
		ActivityAssignment activityAssignment) throws SystemException {
		activityAssignment.setNew(true);

		return activityAssignmentPersistence.update(activityAssignment);
	}

	/**
	 * Creates a new activity assignment with the primary key. Does not add the activity assignment to the database.
	 *
	 * @param activityAssignmentId the primary key for the new activity assignment
	 * @return the new activity assignment
	 */
	@Override
	public ActivityAssignment createActivityAssignment(
		long activityAssignmentId) {
		return activityAssignmentPersistence.create(activityAssignmentId);
	}

	/**
	 * Deletes the activity assignment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param activityAssignmentId the primary key of the activity assignment
	 * @return the activity assignment that was removed
	 * @throws PortalException if a activity assignment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ActivityAssignment deleteActivityAssignment(
		long activityAssignmentId) throws PortalException, SystemException {
		return activityAssignmentPersistence.remove(activityAssignmentId);
	}

	/**
	 * Deletes the activity assignment from the database. Also notifies the appropriate model listeners.
	 *
	 * @param activityAssignment the activity assignment
	 * @return the activity assignment that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ActivityAssignment deleteActivityAssignment(
		ActivityAssignment activityAssignment) throws SystemException {
		return activityAssignmentPersistence.remove(activityAssignment);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ActivityAssignment.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return activityAssignmentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.timetracking.activities.model.impl.ActivityAssignmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return activityAssignmentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.timetracking.activities.model.impl.ActivityAssignmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return activityAssignmentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return activityAssignmentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return activityAssignmentPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ActivityAssignment fetchActivityAssignment(long activityAssignmentId)
		throws SystemException {
		return activityAssignmentPersistence.fetchByPrimaryKey(activityAssignmentId);
	}

	/**
	 * Returns the activity assignment with the primary key.
	 *
	 * @param activityAssignmentId the primary key of the activity assignment
	 * @return the activity assignment
	 * @throws PortalException if a activity assignment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public ActivityAssignment getActivityAssignment(long activityAssignmentId)
		throws PortalException, SystemException {
		return activityAssignmentPersistence.findByPrimaryKey(activityAssignmentId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return activityAssignmentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the activity assignments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.timetracking.activities.model.impl.ActivityAssignmentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of activity assignments
	 * @param end the upper bound of the range of activity assignments (not inclusive)
	 * @return the range of activity assignments
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ActivityAssignment> getActivityAssignments(int start, int end)
		throws SystemException {
		return activityAssignmentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of activity assignments.
	 *
	 * @return the number of activity assignments
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getActivityAssignmentsCount() throws SystemException {
		return activityAssignmentPersistence.countAll();
	}

	/**
	 * Updates the activity assignment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param activityAssignment the activity assignment
	 * @return the activity assignment that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ActivityAssignment updateActivityAssignment(
		ActivityAssignment activityAssignment) throws SystemException {
		return activityAssignmentPersistence.update(activityAssignment);
	}

	/**
	 * Returns the activity local service.
	 *
	 * @return the activity local service
	 */
	public com.liferay.timetracking.activities.service.ActivityLocalService getActivityLocalService() {
		return activityLocalService;
	}

	/**
	 * Sets the activity local service.
	 *
	 * @param activityLocalService the activity local service
	 */
	public void setActivityLocalService(
		com.liferay.timetracking.activities.service.ActivityLocalService activityLocalService) {
		this.activityLocalService = activityLocalService;
	}

	/**
	 * Returns the activity remote service.
	 *
	 * @return the activity remote service
	 */
	public com.liferay.timetracking.activities.service.ActivityService getActivityService() {
		return activityService;
	}

	/**
	 * Sets the activity remote service.
	 *
	 * @param activityService the activity remote service
	 */
	public void setActivityService(
		com.liferay.timetracking.activities.service.ActivityService activityService) {
		this.activityService = activityService;
	}

	/**
	 * Returns the activity persistence.
	 *
	 * @return the activity persistence
	 */
	public ActivityPersistence getActivityPersistence() {
		return activityPersistence;
	}

	/**
	 * Sets the activity persistence.
	 *
	 * @param activityPersistence the activity persistence
	 */
	public void setActivityPersistence(ActivityPersistence activityPersistence) {
		this.activityPersistence = activityPersistence;
	}

	/**
	 * Returns the activity assignment local service.
	 *
	 * @return the activity assignment local service
	 */
	public com.liferay.timetracking.activities.service.ActivityAssignmentLocalService getActivityAssignmentLocalService() {
		return activityAssignmentLocalService;
	}

	/**
	 * Sets the activity assignment local service.
	 *
	 * @param activityAssignmentLocalService the activity assignment local service
	 */
	public void setActivityAssignmentLocalService(
		com.liferay.timetracking.activities.service.ActivityAssignmentLocalService activityAssignmentLocalService) {
		this.activityAssignmentLocalService = activityAssignmentLocalService;
	}

	/**
	 * Returns the activity assignment remote service.
	 *
	 * @return the activity assignment remote service
	 */
	public com.liferay.timetracking.activities.service.ActivityAssignmentService getActivityAssignmentService() {
		return activityAssignmentService;
	}

	/**
	 * Sets the activity assignment remote service.
	 *
	 * @param activityAssignmentService the activity assignment remote service
	 */
	public void setActivityAssignmentService(
		com.liferay.timetracking.activities.service.ActivityAssignmentService activityAssignmentService) {
		this.activityAssignmentService = activityAssignmentService;
	}

	/**
	 * Returns the activity assignment persistence.
	 *
	 * @return the activity assignment persistence
	 */
	public ActivityAssignmentPersistence getActivityAssignmentPersistence() {
		return activityAssignmentPersistence;
	}

	/**
	 * Sets the activity assignment persistence.
	 *
	 * @param activityAssignmentPersistence the activity assignment persistence
	 */
	public void setActivityAssignmentPersistence(
		ActivityAssignmentPersistence activityAssignmentPersistence) {
		this.activityAssignmentPersistence = activityAssignmentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.liferay.timetracking.activities.model.ActivityAssignment",
			activityAssignmentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.timetracking.activities.model.ActivityAssignment");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ActivityAssignment.class;
	}

	protected String getModelClassName() {
		return ActivityAssignment.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = activityAssignmentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.timetracking.activities.service.ActivityLocalService.class)
	protected com.liferay.timetracking.activities.service.ActivityLocalService activityLocalService;
	@BeanReference(type = com.liferay.timetracking.activities.service.ActivityService.class)
	protected com.liferay.timetracking.activities.service.ActivityService activityService;
	@BeanReference(type = ActivityPersistence.class)
	protected ActivityPersistence activityPersistence;
	@BeanReference(type = com.liferay.timetracking.activities.service.ActivityAssignmentLocalService.class)
	protected com.liferay.timetracking.activities.service.ActivityAssignmentLocalService activityAssignmentLocalService;
	@BeanReference(type = com.liferay.timetracking.activities.service.ActivityAssignmentService.class)
	protected com.liferay.timetracking.activities.service.ActivityAssignmentService activityAssignmentService;
	@BeanReference(type = ActivityAssignmentPersistence.class)
	protected ActivityAssignmentPersistence activityAssignmentPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ActivityAssignmentLocalServiceClpInvoker _clpInvoker = new ActivityAssignmentLocalServiceClpInvoker();
}