/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaskAssignment service. Represents a row in the &quot;TaskAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.model.impl.TaskAssignmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.model.impl.TaskAssignmentImpl}.
 * </p>
 *
 * @author BénaBéla
 * @see TaskAssignment
 * @see com.liferay.timetracking.model.impl.TaskAssignmentImpl
 * @see com.liferay.timetracking.model.impl.TaskAssignmentModelImpl
 * @generated
 */
public interface TaskAssignmentModel extends BaseModel<TaskAssignment>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task assignment model instance should use the {@link TaskAssignment} interface instead.
	 */

	/**
	 * Returns the primary key of this task assignment.
	 *
	 * @return the primary key of this task assignment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task assignment.
	 *
	 * @param primaryKey the primary key of this task assignment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task assignment ID of this task assignment.
	 *
	 * @return the task assignment ID of this task assignment
	 */
	public long getTaskAssignmentId();

	/**
	 * Sets the task assignment ID of this task assignment.
	 *
	 * @param taskAssignmentId the task assignment ID of this task assignment
	 */
	public void setTaskAssignmentId(long taskAssignmentId);

	/**
	 * Returns the task ID of this task assignment.
	 *
	 * @return the task ID of this task assignment
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task assignment.
	 *
	 * @param taskId the task ID of this task assignment
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the work day ID of this task assignment.
	 *
	 * @return the work day ID of this task assignment
	 */
	public long getWorkDayId();

	/**
	 * Sets the work day ID of this task assignment.
	 *
	 * @param workDayId the work day ID of this task assignment
	 */
	public void setWorkDayId(long workDayId);

	/**
	 * Returns the start time of this task assignment.
	 *
	 * @return the start time of this task assignment
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this task assignment.
	 *
	 * @param startTime the start time of this task assignment
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this task assignment.
	 *
	 * @return the end time of this task assignment
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this task assignment.
	 *
	 * @param endTime the end time of this task assignment
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the company ID of this task assignment.
	 *
	 * @return the company ID of this task assignment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task assignment.
	 *
	 * @param companyId the company ID of this task assignment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this task assignment.
	 *
	 * @return the group ID of this task assignment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task assignment.
	 *
	 * @param groupId the group ID of this task assignment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this task assignment.
	 *
	 * @return the user ID of this task assignment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task assignment.
	 *
	 * @param userId the user ID of this task assignment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task assignment.
	 *
	 * @return the user uuid of this task assignment
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this task assignment.
	 *
	 * @param userUuid the user uuid of this task assignment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task assignment.
	 *
	 * @return the user name of this task assignment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task assignment.
	 *
	 * @param userName the user name of this task assignment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task assignment.
	 *
	 * @return the create date of this task assignment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task assignment.
	 *
	 * @param createDate the create date of this task assignment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task assignment.
	 *
	 * @return the modified date of this task assignment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task assignment.
	 *
	 * @param modifiedDate the modified date of this task assignment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskAssignment taskAssignment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskAssignment> toCacheModel();

	@Override
	public TaskAssignment toEscapedModel();

	@Override
	public TaskAssignment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}