/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkDay service. Represents a row in the &quot;TimeTracking_WorkDay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timetracking.timesheet.model.impl.WorkDayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timetracking.timesheet.model.impl.WorkDayImpl}.
 * </p>
 *
 * @author Laszlo Hudak, Istvan Sajtos
 * @see WorkDay
 * @see com.liferay.timetracking.timesheet.model.impl.WorkDayImpl
 * @see com.liferay.timetracking.timesheet.model.impl.WorkDayModelImpl
 * @generated
 */
public interface WorkDayModel extends AuditedModel, BaseModel<WorkDay> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work day model instance should use the {@link WorkDay} interface instead.
	 */

	/**
	 * Returns the primary key of this work day.
	 *
	 * @return the primary key of this work day
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work day.
	 *
	 * @param primaryKey the primary key of this work day
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work day ID of this work day.
	 *
	 * @return the work day ID of this work day
	 */
	public long getWorkDayId();

	/**
	 * Sets the work day ID of this work day.
	 *
	 * @param workDayId the work day ID of this work day
	 */
	public void setWorkDayId(long workDayId);

	/**
	 * Returns the company ID of this work day.
	 *
	 * @return the company ID of this work day
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this work day.
	 *
	 * @param companyId the company ID of this work day
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this work day.
	 *
	 * @return the user ID of this work day
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this work day.
	 *
	 * @param userId the user ID of this work day
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work day.
	 *
	 * @return the user uuid of this work day
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this work day.
	 *
	 * @param userUuid the user uuid of this work day
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this work day.
	 *
	 * @return the user name of this work day
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this work day.
	 *
	 * @param userName the user name of this work day
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this work day.
	 *
	 * @return the create date of this work day
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this work day.
	 *
	 * @param createDate the create date of this work day
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this work day.
	 *
	 * @return the modified date of this work day
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work day.
	 *
	 * @param modifiedDate the modified date of this work day
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the day of year ID of this work day.
	 *
	 * @return the day of year ID of this work day
	 */
	public long getDayOfYearId();

	/**
	 * Sets the day of year ID of this work day.
	 *
	 * @param dayOfYearId the day of year ID of this work day
	 */
	public void setDayOfYearId(long dayOfYearId);

	/**
	 * Returns the start time of this work day.
	 *
	 * @return the start time of this work day
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this work day.
	 *
	 * @param startTime the start time of this work day
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this work day.
	 *
	 * @return the end time of this work day
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this work day.
	 *
	 * @param endTime the end time of this work day
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the pause of this work day.
	 *
	 * @return the pause of this work day
	 */
	public int getPause();

	/**
	 * Sets the pause of this work day.
	 *
	 * @param pause the pause of this work day
	 */
	public void setPause(int pause);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkDay workDay);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkDay> toCacheModel();

	@Override
	public WorkDay toEscapedModel();

	@Override
	public WorkDay toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}