/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timetracking.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.timetracking.model.TaskAssignment;
import com.liferay.timetracking.model.TaskAssignmentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TaskAssignment service. Represents a row in the &quot;TaskAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.timetracking.model.TaskAssignmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskAssignmentImpl}.
 * </p>
 *
 * @author BénaBéla
 * @see TaskAssignmentImpl
 * @see com.liferay.timetracking.model.TaskAssignment
 * @see com.liferay.timetracking.model.TaskAssignmentModel
 * @generated
 */
public class TaskAssignmentModelImpl extends BaseModelImpl<TaskAssignment>
	implements TaskAssignmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task assignment model instance should use the {@link com.liferay.timetracking.model.TaskAssignment} interface instead.
	 */
	public static final String TABLE_NAME = "TaskAssignment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "taskAssignmentId", Types.BIGINT },
			{ "taskId", Types.BIGINT },
			{ "workDayId", Types.BIGINT },
			{ "startTime", Types.TIMESTAMP },
			{ "endTime", Types.TIMESTAMP },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table TaskAssignment (taskAssignmentId LONG not null primary key,taskId LONG,workDayId LONG,startTime DATE null,endTime DATE null,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table TaskAssignment";
	public static final String ORDER_BY_JPQL = " ORDER BY taskAssignment.taskAssignmentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TaskAssignment.taskAssignmentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.timetracking.model.TaskAssignment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.timetracking.model.TaskAssignment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.timetracking.model.TaskAssignment"),
			true);
	public static long TASKASSIGNMENTID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.timetracking.model.TaskAssignment"));

	public TaskAssignmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskAssignmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskAssignmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskAssignmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskAssignment.class;
	}

	@Override
	public String getModelClassName() {
		return TaskAssignment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("taskAssignmentId", getTaskAssignmentId());
		attributes.put("taskId", getTaskId());
		attributes.put("workDayId", getWorkDayId());
		attributes.put("startTime", getStartTime());
		attributes.put("endTime", getEndTime());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long taskAssignmentId = (Long)attributes.get("taskAssignmentId");

		if (taskAssignmentId != null) {
			setTaskAssignmentId(taskAssignmentId);
		}

		Long taskId = (Long)attributes.get("taskId");

		if (taskId != null) {
			setTaskId(taskId);
		}

		Long workDayId = (Long)attributes.get("workDayId");

		if (workDayId != null) {
			setWorkDayId(workDayId);
		}

		Date startTime = (Date)attributes.get("startTime");

		if (startTime != null) {
			setStartTime(startTime);
		}

		Date endTime = (Date)attributes.get("endTime");

		if (endTime != null) {
			setEndTime(endTime);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public long getTaskAssignmentId() {
		return _taskAssignmentId;
	}

	@Override
	public void setTaskAssignmentId(long taskAssignmentId) {
		_columnBitmask = -1L;

		if (!_setOriginalTaskAssignmentId) {
			_setOriginalTaskAssignmentId = true;

			_originalTaskAssignmentId = _taskAssignmentId;
		}

		_taskAssignmentId = taskAssignmentId;
	}

	public long getOriginalTaskAssignmentId() {
		return _originalTaskAssignmentId;
	}

	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		_taskId = taskId;
	}

	@Override
	public long getWorkDayId() {
		return _workDayId;
	}

	@Override
	public void setWorkDayId(long workDayId) {
		_workDayId = workDayId;
	}

	@Override
	public Date getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(Date startTime) {
		_startTime = startTime;
	}

	@Override
	public Date getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(Date endTime) {
		_endTime = endTime;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TaskAssignment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskAssignment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TaskAssignment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskAssignmentImpl taskAssignmentImpl = new TaskAssignmentImpl();

		taskAssignmentImpl.setTaskAssignmentId(getTaskAssignmentId());
		taskAssignmentImpl.setTaskId(getTaskId());
		taskAssignmentImpl.setWorkDayId(getWorkDayId());
		taskAssignmentImpl.setStartTime(getStartTime());
		taskAssignmentImpl.setEndTime(getEndTime());
		taskAssignmentImpl.setCompanyId(getCompanyId());
		taskAssignmentImpl.setGroupId(getGroupId());
		taskAssignmentImpl.setUserId(getUserId());
		taskAssignmentImpl.setUserName(getUserName());
		taskAssignmentImpl.setCreateDate(getCreateDate());
		taskAssignmentImpl.setModifiedDate(getModifiedDate());

		taskAssignmentImpl.resetOriginalValues();

		return taskAssignmentImpl;
	}

	@Override
	public int compareTo(TaskAssignment taskAssignment) {
		int value = 0;

		if (getTaskAssignmentId() < taskAssignment.getTaskAssignmentId()) {
			value = -1;
		}
		else if (getTaskAssignmentId() > taskAssignment.getTaskAssignmentId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaskAssignment)) {
			return false;
		}

		TaskAssignment taskAssignment = (TaskAssignment)obj;

		long primaryKey = taskAssignment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TaskAssignmentModelImpl taskAssignmentModelImpl = this;

		taskAssignmentModelImpl._originalTaskAssignmentId = taskAssignmentModelImpl._taskAssignmentId;

		taskAssignmentModelImpl._setOriginalTaskAssignmentId = false;

		taskAssignmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskAssignment> toCacheModel() {
		TaskAssignmentCacheModel taskAssignmentCacheModel = new TaskAssignmentCacheModel();

		taskAssignmentCacheModel.taskAssignmentId = getTaskAssignmentId();

		taskAssignmentCacheModel.taskId = getTaskId();

		taskAssignmentCacheModel.workDayId = getWorkDayId();

		Date startTime = getStartTime();

		if (startTime != null) {
			taskAssignmentCacheModel.startTime = startTime.getTime();
		}
		else {
			taskAssignmentCacheModel.startTime = Long.MIN_VALUE;
		}

		Date endTime = getEndTime();

		if (endTime != null) {
			taskAssignmentCacheModel.endTime = endTime.getTime();
		}
		else {
			taskAssignmentCacheModel.endTime = Long.MIN_VALUE;
		}

		taskAssignmentCacheModel.companyId = getCompanyId();

		taskAssignmentCacheModel.groupId = getGroupId();

		taskAssignmentCacheModel.userId = getUserId();

		taskAssignmentCacheModel.userName = getUserName();

		String userName = taskAssignmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taskAssignmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskAssignmentCacheModel.createDate = createDate.getTime();
		}
		else {
			taskAssignmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskAssignmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskAssignmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return taskAssignmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{taskAssignmentId=");
		sb.append(getTaskAssignmentId());
		sb.append(", taskId=");
		sb.append(getTaskId());
		sb.append(", workDayId=");
		sb.append(getWorkDayId());
		sb.append(", startTime=");
		sb.append(getStartTime());
		sb.append(", endTime=");
		sb.append(getEndTime());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.timetracking.model.TaskAssignment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>taskAssignmentId</column-name><column-value><![CDATA[");
		sb.append(getTaskAssignmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taskId</column-name><column-value><![CDATA[");
		sb.append(getTaskId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workDayId</column-name><column-value><![CDATA[");
		sb.append(getWorkDayId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startTime</column-name><column-value><![CDATA[");
		sb.append(getStartTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endTime</column-name><column-value><![CDATA[");
		sb.append(getEndTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TaskAssignment.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TaskAssignment.class
		};
	private long _taskAssignmentId;
	private long _originalTaskAssignmentId;
	private boolean _setOriginalTaskAssignmentId;
	private long _taskId;
	private long _workDayId;
	private Date _startTime;
	private Date _endTime;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private TaskAssignment _escapedModel;
}